### PR TITLE
chore: upgrade to ember v3.16.2

### PR DESCRIPTION
**Pull request by derrabauke**
## Contents

This bumps ember to v3.16.2 and linted the complete codebase. Further it contains some minor fixes of some `scheduleOnce` function calls.

---
**Only merge when #709 is merged!**

PRs of this series will be merged into the `ember-octance` branch.
All the single PRs get summarized in #710 onto `master`.

[](https://mermaid.live/edit#pako:eNqdkjFvgzAQhf-KdV0TC8jGXFR1qBQRqV28OHCAFWwj9xhQlP9eg5vSQCpF9YS5995n6d4ZClsipFArenGya4Rh_hRWa0VMlakA61StjABGsvbXhMd8JyDojk6aomGoj-i2tiBp8DugweJke2Jaeu8ik4mJyjm_5tzMRguh8ck4zheBa5ZGV-MEYjR0mObZe5YfspsX7vNttAj69Wuih-8HabN5iYnXmHiNeQQQ333RPJiZyVqT_I-ZrPf_8bqf1_DEKmVk2w5_rjlE3WlEiAwl2vGIRwJgA17uvaVv4HnUCaAGtd_7WIQSK9m3NNIvXtp3pSTMSkXWQVrJ9hM3IHuyh8EUkJLr8Sp6VrJ2Uv-ocDK9hapPjb98AXwr8lw)

### CODE REVIEW

**Comment by anehx** [comment]
Isn't this an upgrade to `3.16`? The code would suggest so..

**Comment by derrabauke** [comment]
> Isn't this an upgrade to `3.16`? The code would suggest so..

I split it up and put `Draft:` into the title. Work in progress ;-) 
Will ping when ready.

**Comment by derrabauke** [comment]
> > Isn't this an upgrade to `3.16`? The code would suggest so..
> 
> I split it up and put `Draft:` into the title. Work in progress ;-) Will ping when ready.

@anehx now it's ready.

**Comment by anehx** [comment]
@derrabauke Alright, I'll look into it today. For the next time: I'd appreciate being assigned only when the PR is ready, otherwise the reviewers will be spamed for something they don't need to know yet. Also, there's a draft feature in github.

**Comment by derrabauke** [comment]
> @derrabauke Alright, I'll look into it today. For the next time: I'd appreciate being assigned only when the PR is ready, otherwise the reviewers will be spamed for something they don't need to know yet. Also, there's a draft feature in github.

Yes, you are totally right. Sorry for the inconvenience!

**Comment by derrabauke** [comment]
@Yelinz # 1

**Review by Yelinz — APPROVED** [review]
Still a lot of `.get` left, but should be resolved in the next few PRs right?

**Comment by derrabauke** [comment]
> Still a lot of `.get` left, but should be resolved in the next few PRs right?

Yes, exactley. :+1:  There are some [codemods commits coming which including es5-getter modification](https://github.com/adfinis/timed-frontend/commit/273376706234dc01f5e393591b17d911fe4709a2).

**Pull request merged**
