### PR TITLE
feat(analysis): accountants may bill reports

### PR DESCRIPTION
**Pull request by trowik**
This will allow accountants to bill reports on analysis-edit. All
form elements except the `billed` checkbox will be disabled
if at least 1 report has been selected that was not created by the
accountant.

### CODE REVIEW

**Comment by trowik** [comment]
Need to add tests

**Comment by aziiee** [comment]
@trowik can you please also write an acceptance test in analysis-edit for this?

**Comment by trowik** [comment]
Will do

**Comment by aziiee** [comment]
Okay so with this, accountants will be able to edit everything in a report. How about restricting this so they can only edit the billed flag and everything else stays disabled? They should not be able to edit all other informations, that's the job of the assignees.

Can I also have your point of view on this @anehx @kaldras?

**Comment by anehx** [comment]
> Okay so with this, accountants will be able to edit everything in a report. How about restricting this so they can only edit the billed flag and everything else stays disabled? They should not be able to edit all other informations, that's the job of the assignees.
> 
> Can I also have your point of view on this @anehx @kaldras?

@aziiee your approach seems more reasonable, let's do that.

**Comment by trowik** [comment]
@aziiee ah yes. That's definitely a better approach

**Comment by velrest** [comment]
@trowik whats the status with this pr?

**Comment by trowik** [comment]
I thought that it was already merged, but it looks like it still needs a final review. @velrest

**Review by velrest — APPROVED** [review]

**Pull request merged**
