### PR TITLE
chore(deps): upgrades and migration to auto-import v2

### PR DESCRIPTION
**Pull request by derrabauke**
## Contents:
* 542956b chore(deps): migrate to @fontsource package
* a433a16 chore(deps): migrate to auto-import v2
* dc009c5 chore(deps): minor updates
* f6ef643 chore(deps): patch-level updates
* 19492cd chore(deps): add ember-cli-deprecation-workflow

The contents of this PR start at 19492cd
Commits before belong to #718

---

### CODE REVIEW

**Comment by derrabauke** [comment]
:ping_pong: @luytena :upside_down_face:

**Review by luytena — COMMENTED** [review]
I see a couple of major upgrades in the dependencies, did you check for migration guides? If yes, it looks good to me :+1:

**Comment by velrest** [comment]
@derrabauke Sorry for dropping in out of nowhere here, but what is the purpose of `ember-cli-dependency-checker` doesn't yarn already provide this functionality?

**Comment by derrabauke** [comment]
> I see a couple of major upgrades in the dependencies, did you check for migration guides? If yes, it looks good to me +1

yep, this is mainly due to the `ember-auto-import` upgrade. Checked every package and there is nothing to do.

**Comment by derrabauke** [comment]
> @derrabauke Sorry for dropping in out of nowhere here, but what is the purpose of `ember-cli-dependency-checker` doesn't yarn already provide this functionality?

I srsly have no idea why this package is there and was unsure if we can delete it or if it's good for any use case. :shrug: 
Should we throw it out?

**Comment by derrabauke** [comment]
> > @derrabauke Sorry for dropping in out of nowhere here, but what is the purpose of `ember-cli-dependency-checker` doesn't yarn already provide this functionality?
> 
> @velrest I srsly have no idea why this package is there and was unsure if we can delete it or if it's good for any use case. shrug Should we throw it out?

Deleted it. Also had to add a resolution for `@embroider/macros`, otherwise the build pipeline gets stuck. Minimum version together with `auto-import-v2` is `v0.50.0`.

**Comment by velrest** [comment]
> > > @derrabauke Sorry for dropping in out of nowhere here, but what is the purpose of `ember-cli-dependency-checker` doesn't yarn already provide this functionality?
> > 
> > 
> > @velrest I srsly have no idea why this package is there and was unsure if we can delete it or if it's good for any use case. shrug Should we throw it out?
> 
> Deleted it. Also had to add a resolution for `@embroider/macros`, otherwise the build pipeline gets stuck. Minimum version together with `auto-import-v2` is `v0.50.0`.

Nice! Was `ember-cli-deprecation-workflow` intentionally added?

**Comment by derrabauke** [comment]
> > > > @derrabauke Sorry for dropping in out of nowhere here, but what is the purpose of `ember-cli-dependency-checker` doesn't yarn already provide this functionality?
> > > 
> > > 
> > > @velrest I srsly have no idea why this package is there and was unsure if we can delete it or if it's good for any use case. shrug Should we throw it out?
> > 
> > 
> > Deleted it. Also had to add a resolution for `@embroider/macros`, otherwise the build pipeline gets stuck. Minimum version together with `auto-import-v2` is `v0.50.0`.
> 
> @derrabauke Nice! Was `ember-cli-deprecation-workflow` intentionally added?

Yes! Helps keeping the build-output and console clean until I'm ready to tackle the certain deprecations. Will be one of the last steps I guess. In the end of the PR-row it will get removed again.

**Review by velrest — APPROVED** [review]

**Pull request merged**
